spring:
  application:
    name: AccountService
  datasource:
    url: jdbc:mysql://localhost:3306/bank-account
    
server:
  port: 8100
  
hystrix:
  command:
    default:
      circuitBreaker:
        errorThresholdPercentage: 50
        requestVolumeThreshold: 4
        sleepWindowInMilliseconds: 60000
      metrics:
        rollingStats:
          timeInMilliseconds: 10000