spring:
  datasource:
    password: root
    username: Krishna@9097
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
 database-platform: org.hibernate.dialect.MySQL8Dialect
  sleuth:
    sampler:
      percentage: 1.0
  zipkin:
    base-url: http://localhost:9411/

eureka:
  client:
    service-url:
      defaultZone: http://localhost:2222/eureka, http://localhost:2223/eureka, http://localhost:2224/eureka

#Logging configuration
logging:
  file: 
    name: Errorlog_dev.log
  pattern:
    file: "%d{yyyy-MM-dd HH:mm:ss,SSS} %5p [%t] %c [%M] - %m%n"
