spring:
  datasource:
    driverClassName: com.mysql.cj.jdbc.Driver
    password: root
    username: root
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
  zipkin:
    base-url: http://localhost:9411/

eureka:
  client:
    service-url:
      defaultZone: http://localhost:2222/eureka, http://localhost:2223/eureka, http://localhost:2224/eureka

#Logging configuration
logging:
  file: 
    name: Errorlog_dev.log
  pattern:
    file: "%d{yyyy-MM-dd HH:mm:ss,SSS} %5p [%t] %c [%M] - %m%n"