spring:
  datasource:
    driverClassName: com.mysql.cj.jdbc.Driver
    password: root
    username: root
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

eureka:
  client:
    service-url:
      defaultZone: http://localhost:2200/eureka, http://localhost:2300/eureka, http://localhost:2400/eureka

#Logging configuration
logging:
  file: Errorlog_dev.log
  pattern:
    file: "%d{yyyy-MM-dd HH:mm:ss,SSS} %5p [%t] %c [%M] - %m%n"