account:
  port: 8100
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/bank?user=user&password=password&useUnicode=true&useJDBCCompliantTimezoneShift=true&useLegacyDatetimeCode=false&serverTimezone=UTC";
server:
  port: 8400
